"""add_transaction_id_to_payments

Revision ID: e2ffcf1a045b
Revises: 39f4f628a0e2
Create Date: 2026-06-07 02:52:05.323140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ffcf1a045b'
down_revision: Union[str, None] = '39f4f628a0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'transaction_id')
    # ### end Alembic commands ###
